 export const ADD_MESSAGE = "ADD_MESSAGE"
 export const CHANGE_MESSAGE = "CHANGE_MESSAGE"
 export const ADDPOST = "ADDPOST"
 export const UPDATEPOST = "UPDATEPOST"
 export const GET_USERS = "GET_USERS"
 export const DELETEPOST = "DELETEPOST"
 export const GET_MESSAGES = "GET_MESSAGES"
 export const GET_MESSAGES_ID = " GET_MESSAGES_ID"
 export const REQUEST_START = "REQUEST_START"
 export const DISABLE_INPUT = "DISABLE_INPUT"
 